"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.flavor_view import FlavorView
from openapi_client.model.instance_variant_view import InstanceVariantView
globals()['FlavorView'] = FlavorView
globals()['InstanceVariantView'] = InstanceVariantView
from openapi_client.model.instance_view import InstanceView


class TestInstanceView(unittest.TestCase):
    """InstanceView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceView(self):
        """Test InstanceView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
