"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.addon_feature_instance_view import AddonFeatureInstanceView


class TestAddonFeatureInstanceView(unittest.TestCase):
    """AddonFeatureInstanceView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddonFeatureInstanceView(self):
        """Test AddonFeatureInstanceView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddonFeatureInstanceView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
