"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.github_webhook_pusher import GithubWebhookPusher


class TestGithubWebhookPusher(unittest.TestCase):
    """GithubWebhookPusher unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGithubWebhookPusher(self):
        """Test GithubWebhookPusher"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GithubWebhookPusher()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
