"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ask_for_password_reset_via_form(self):
        """Test case for ask_for_password_reset_via_form

        """
        pass

    def test_authorize_paypal_transaction(self):
        """Test case for authorize_paypal_transaction

        """
        pass

    def test_cancel_paypal_transaction(self):
        """Test case for cancel_paypal_transaction

        """
        pass

    def test_confirm_password_reset_request(self):
        """Test case for confirm_password_reset_request

        """
        pass

    def test_create_user_from_form(self):
        """Test case for create_user_from_form

        """
        pass

    def test_delete_github_link(self):
        """Test case for delete_github_link

        """
        pass

    def test_finsih_github_signup(self):
        """Test case for finsih_github_signup

        """
        pass

    def test_get_applications(self):
        """Test case for get_applications

        """
        pass

    def test_get_env(self):
        """Test case for get_env

        """
        pass

    def test_get_git_info(self):
        """Test case for get_git_info

        """
        pass

    def test_get_github(self):
        """Test case for get_github

        """
        pass

    def test_get_github_applications(self):
        """Test case for get_github_applications

        """
        pass

    def test_get_github_callback(self):
        """Test case for get_github_callback

        """
        pass

    def test_get_github_emails(self):
        """Test case for get_github_emails

        """
        pass

    def test_get_github_keys(self):
        """Test case for get_github_keys

        """
        pass

    def test_get_github_link(self):
        """Test case for get_github_link

        """
        pass

    def test_get_github_login(self):
        """Test case for get_github_login

        """
        pass

    def test_get_github_username(self):
        """Test case for get_github_username

        """
        pass

    def test_get_login_form(self):
        """Test case for get_login_form

        """
        pass

    def test_get_login_form1(self):
        """Test case for get_login_form1

        """
        pass

    def test_get_password_forgotten_form(self):
        """Test case for get_password_forgotten_form

        """
        pass

    def test_get_signup_form(self):
        """Test case for get_signup_form

        """
        pass

    def test_get_signup_form1(self):
        """Test case for get_signup_form1

        """
        pass

    def test_get_user_by_id(self):
        """Test case for get_user_by_id

        """
        pass

    def test_github_signup(self):
        """Test case for github_signup

        """
        pass

    def test_login(self):
        """Test case for login

        """
        pass

    def test_login1(self):
        """Test case for login1

        """
        pass

    def test_mfa_login(self):
        """Test case for mfa_login

        """
        pass

    def test_mfa_login1(self):
        """Test case for mfa_login1

        """
        pass

    def test_post_github_redeploy(self):
        """Test case for post_github_redeploy

        """
        pass

    def test_reset_password_forgotten(self):
        """Test case for reset_password_forgotten

        """
        pass

    def test_update_env(self):
        """Test case for update_env

        """
        pass

    def test_update_invoice(self):
        """Test case for update_invoice

        """
        pass


if __name__ == '__main__':
    unittest.main()
