"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.addon_feature_view import AddonFeatureView
from openapi_client.model.addon_plan_view import AddonPlanView
globals()['AddonFeatureView'] = AddonFeatureView
globals()['AddonPlanView'] = AddonPlanView
from openapi_client.model.addon_provider_info_full_view import AddonProviderInfoFullView


class TestAddonProviderInfoFullView(unittest.TestCase):
    """AddonProviderInfoFullView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddonProviderInfoFullView(self):
        """Test AddonProviderInfoFullView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddonProviderInfoFullView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
