"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.wannabe_addon_provider_api import WannabeAddonProviderAPI
globals()['WannabeAddonProviderAPI'] = WannabeAddonProviderAPI
from openapi_client.model.wannabe_addon_provider import WannabeAddonProvider


class TestWannabeAddonProvider(unittest.TestCase):
    """WannabeAddonProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWannabeAddonProvider(self):
        """Test WannabeAddonProvider"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WannabeAddonProvider()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
