"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.invoice_line_rendering import InvoiceLineRendering
from openapi_client.model.organisation_member_view import OrganisationMemberView
globals()['InvoiceLineRendering'] = InvoiceLineRendering
globals()['OrganisationMemberView'] = OrganisationMemberView
from openapi_client.model.invoice_rendering import InvoiceRendering


class TestInvoiceRendering(unittest.TestCase):
    """InvoiceRendering unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvoiceRendering(self):
        """Test InvoiceRendering"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvoiceRendering()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
