"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.deployment_info_view import DeploymentInfoView


class TestDeploymentInfoView(unittest.TestCase):
    """DeploymentInfoView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeploymentInfoView(self):
        """Test DeploymentInfoView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeploymentInfoView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
