"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.wannabe_oauth_app import WannabeOauthApp
globals()['WannabeOauthApp'] = WannabeOauthApp
from openapi_client.model.wannabe_application import WannabeApplication


class TestWannabeApplication(unittest.TestCase):
    """WannabeApplication unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWannabeApplication(self):
        """Test WannabeApplication"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WannabeApplication()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
