"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.o_auth1_consumer_view import OAuth1ConsumerView
from openapi_client.model.o_auth_rights_view import OAuthRightsView
globals()['OAuth1ConsumerView'] = OAuth1ConsumerView
globals()['OAuthRightsView'] = OAuthRightsView
from openapi_client.model.o_auth1_access_token_view import OAuth1AccessTokenView


class TestOAuth1AccessTokenView(unittest.TestCase):
    """OAuth1AccessTokenView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth1AccessTokenView(self):
        """Test OAuth1AccessTokenView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OAuth1AccessTokenView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
