"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.self_api import SelfApi  # noqa: E501


class TestSelfApi(unittest.TestCase):
    """SelfApi unit test stubs"""

    def setUp(self):
        self.api = SelfApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_email_address(self):
        """Test case for add_email_address

        """
        pass

    def test_add_self_addon_tag_by_addon_id(self):
        """Test case for add_self_addon_tag_by_addon_id

        """
        pass

    def test_add_self_application(self):
        """Test case for add_self_application

        """
        pass

    def test_add_self_application_dependency_by_app_id(self):
        """Test case for add_self_application_dependency_by_app_id

        """
        pass

    def test_add_self_application_tag_by_app_id(self):
        """Test case for add_self_application_tag_by_app_id

        """
        pass

    def test_add_self_payment_method(self):
        """Test case for add_self_payment_method

        """
        pass

    def test_add_self_vhost_by_app_id(self):
        """Test case for add_self_vhost_by_app_id

        """
        pass

    def test_add_ssh_key(self):
        """Test case for add_ssh_key

        """
        pass

    def test_buy_self_drops(self):
        """Test case for buy_self_drops

        """
        pass

    def test_cancel_deploy(self):
        """Test case for cancel_deploy

        """
        pass

    def test_change_self_addon_plan_by_addon_id(self):
        """Test case for change_self_addon_plan_by_addon_id

        """
        pass

    def test_change_user_password(self):
        """Test case for change_user_password

        """
        pass

    def test_choose_self_payment_provider(self):
        """Test case for choose_self_payment_provider

        """
        pass

    def test_create_mfa(self):
        """Test case for create_mfa

        """
        pass

    def test_create_self_consumer(self):
        """Test case for create_self_consumer

        """
        pass

    def test_delete_mfa(self):
        """Test case for delete_mfa

        """
        pass

    def test_delete_self_addon_tag_by_addon_id(self):
        """Test case for delete_self_addon_tag_by_addon_id

        """
        pass

    def test_delete_self_application_by_app_id(self):
        """Test case for delete_self_application_by_app_id

        """
        pass

    def test_delete_self_application_dependency_by_app_id(self):
        """Test case for delete_self_application_dependency_by_app_id

        """
        pass

    def test_delete_self_application_tag_app_id(self):
        """Test case for delete_self_application_tag_app_id

        """
        pass

    def test_delete_self_card(self):
        """Test case for delete_self_card

        """
        pass

    def test_delete_self_consumer(self):
        """Test case for delete_self_consumer

        """
        pass

    def test_delete_self_purchase_order(self):
        """Test case for delete_self_purchase_order

        """
        pass

    def test_delete_self_recurrent_payment(self):
        """Test case for delete_self_recurrent_payment

        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        """
        pass

    def test_deprovision_self_addon_by_id(self):
        """Test case for deprovision_self_addon_by_id

        """
        pass

    def test_edit_self_application_by_app_id(self):
        """Test case for edit_self_application_by_app_id

        """
        pass

    def test_edit_self_application_env_by_app_id(self):
        """Test case for edit_self_application_env_by_app_id

        """
        pass

    def test_edit_self_application_env_by_app_id_and_env_name(self):
        """Test case for edit_self_application_env_by_app_id_and_env_name

        """
        pass

    def test_edit_user(self):
        """Test case for edit_user

        """
        pass

    def test_fav_mfa(self):
        """Test case for fav_mfa

        """
        pass

    def test_get_addon_sso_data(self):
        """Test case for get_addon_sso_data

        """
        pass

    def test_get_application_deployment(self):
        """Test case for get_application_deployment

        """
        pass

    def test_get_application_deployments(self):
        """Test case for get_application_deployments

        """
        pass

    def test_get_backup_codes(self):
        """Test case for get_backup_codes

        """
        pass

    def test_get_confirmation_email(self):
        """Test case for get_confirmation_email

        """
        pass

    def test_get_consumptions(self):
        """Test case for get_consumptions

        """
        pass

    def test_get_email_addresses(self):
        """Test case for get_email_addresses

        """
        pass

    def test_get_id(self):
        """Test case for get_id

        """
        pass

    def test_get_self_addon_by_id(self):
        """Test case for get_self_addon_by_id

        """
        pass

    def test_get_self_addon_env_by_addon_id(self):
        """Test case for get_self_addon_env_by_addon_id

        """
        pass

    def test_get_self_addon_tags_by_addon_id(self):
        """Test case for get_self_addon_tags_by_addon_id

        """
        pass

    def test_get_self_addons(self):
        """Test case for get_self_addons

        """
        pass

    def test_get_self_addons_linked_to_application_by_app_id(self):
        """Test case for get_self_addons_linked_to_application_by_app_id

        """
        pass

    def test_get_self_amount(self):
        """Test case for get_self_amount

        """
        pass

    def test_get_self_application_branches_by_app_id(self):
        """Test case for get_self_application_branches_by_app_id

        """
        pass

    def test_get_self_application_by_app_id(self):
        """Test case for get_self_application_by_app_id

        """
        pass

    def test_get_self_application_dependencies_by_app_id(self):
        """Test case for get_self_application_dependencies_by_app_id

        """
        pass

    def test_get_self_application_dependencies_env_by_app_id(self):
        """Test case for get_self_application_dependencies_env_by_app_id

        """
        pass

    def test_get_self_application_dependents(self):
        """Test case for get_self_application_dependents

        """
        pass

    def test_get_self_application_env_by_app_id(self):
        """Test case for get_self_application_env_by_app_id

        """
        pass

    def test_get_self_application_instance_by_app_and_instance_id(self):
        """Test case for get_self_application_instance_by_app_and_instance_id

        """
        pass

    def test_get_self_application_instances_by_app_id(self):
        """Test case for get_self_application_instances_by_app_id

        """
        pass

    def test_get_self_application_tags_by_app_id(self):
        """Test case for get_self_application_tags_by_app_id

        """
        pass

    def test_get_self_applications(self):
        """Test case for get_self_applications

        """
        pass

    def test_get_self_applications_linked_to_addon_by_addon_id(self):
        """Test case for get_self_applications_linked_to_addon_by_addon_id

        """
        pass

    def test_get_self_cli_tokens(self):
        """Test case for get_self_cli_tokens

        """
        pass

    def test_get_self_consumer(self):
        """Test case for get_self_consumer

        """
        pass

    def test_get_self_consumer_secret(self):
        """Test case for get_self_consumer_secret

        """
        pass

    def test_get_self_consumers(self):
        """Test case for get_self_consumers

        """
        pass

    def test_get_self_default_method(self):
        """Test case for get_self_default_method

        """
        pass

    def test_get_self_env_of_addons_linked_to_application_by_app_id(self):
        """Test case for get_self_env_of_addons_linked_to_application_by_app_id

        """
        pass

    def test_get_self_exposed_env_by_app_id(self):
        """Test case for get_self_exposed_env_by_app_id

        """
        pass

    def test_get_self_favourite_vhost_by_app_id(self):
        """Test case for get_self_favourite_vhost_by_app_id

        """
        pass

    def test_get_self_instances_for_all_apps(self):
        """Test case for get_self_instances_for_all_apps

        """
        pass

    def test_get_self_invoice_by_id(self):
        """Test case for get_self_invoice_by_id

        """
        pass

    def test_get_self_invoices(self):
        """Test case for get_self_invoices

        """
        pass

    def test_get_self_monthly_invoice(self):
        """Test case for get_self_monthly_invoice

        """
        pass

    def test_get_self_payment_info(self):
        """Test case for get_self_payment_info

        """
        pass

    def test_get_self_payment_methods(self):
        """Test case for get_self_payment_methods

        """
        pass

    def test_get_self_pdf_invoice_by_id(self):
        """Test case for get_self_pdf_invoice_by_id

        """
        pass

    def test_get_self_price_with_tax(self):
        """Test case for get_self_price_with_tax

        """
        pass

    def test_get_self_recurrent_payment(self):
        """Test case for get_self_recurrent_payment

        """
        pass

    def test_get_self_stripe_token(self):
        """Test case for get_self_stripe_token

        """
        pass

    def test_get_self_tokens(self):
        """Test case for get_self_tokens

        """
        pass

    def test_get_self_vhost_by_app_id(self):
        """Test case for get_self_vhost_by_app_id

        """
        pass

    def test_get_ssh_keys(self):
        """Test case for get_ssh_keys

        """
        pass

    def test_get_summary(self):
        """Test case for get_summary

        """
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_link_self_addon_to_application_by_app_id(self):
        """Test case for link_self_addon_to_application_by_app_id

        """
        pass

    def test_mark_self_favourite_vhost_by_app_id(self):
        """Test case for mark_self_favourite_vhost_by_app_id

        """
        pass

    def test_preorder_self_addon(self):
        """Test case for preorder_self_addon

        """
        pass

    def test_provision_self_addon(self):
        """Test case for provision_self_addon

        """
        pass

    def test_redeploy_self_application_by_app_id(self):
        """Test case for redeploy_self_application_by_app_id

        """
        pass

    def test_remove_email_address(self):
        """Test case for remove_email_address

        """
        pass

    def test_remove_self_application_env_by_app_id_and_env_name(self):
        """Test case for remove_self_application_env_by_app_id_and_env_name

        """
        pass

    def test_remove_self_vhost_by_app_id(self):
        """Test case for remove_self_vhost_by_app_id

        """
        pass

    def test_remove_ssh_key(self):
        """Test case for remove_ssh_key

        """
        pass

    def test_rename_addon(self):
        """Test case for rename_addon

        """
        pass

    def test_revoke_all_tokens(self):
        """Test case for revoke_all_tokens

        """
        pass

    def test_revoke_token(self):
        """Test case for revoke_token

        """
        pass

    def test_set_self_application_branch_by_app_id(self):
        """Test case for set_self_application_branch_by_app_id

        """
        pass

    def test_set_self_build_instance_flavor_by_app_id(self):
        """Test case for set_self_build_instance_flavor_by_app_id

        """
        pass

    def test_set_self_default_method(self):
        """Test case for set_self_default_method

        """
        pass

    def test_set_self_max_credits_per_month(self):
        """Test case for set_self_max_credits_per_month

        """
        pass

    def test_set_user_avatar_from_file(self):
        """Test case for set_user_avatar_from_file

        """
        pass

    def test_undeploy_self_application_by_app_id(self):
        """Test case for undeploy_self_application_by_app_id

        """
        pass

    def test_unlink_selfddon_from_application_by_app_and_addon_id(self):
        """Test case for unlink_selfddon_from_application_by_app_and_addon_id

        """
        pass

    def test_unmark_self_favourite_vhost_by_app_id(self):
        """Test case for unmark_self_favourite_vhost_by_app_id

        """
        pass

    def test_update_self_consumer(self):
        """Test case for update_self_consumer

        """
        pass

    def test_update_self_exposed_env_by_app_id(self):
        """Test case for update_self_exposed_env_by_app_id

        """
        pass

    def test_validate_email(self):
        """Test case for validate_email

        """
        pass

    def test_validate_mfa(self):
        """Test case for validate_mfa

        """
        pass


if __name__ == '__main__':
    unittest.main()
