"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.organisation_api import OrganisationApi  # noqa: E501


class TestOrganisationApi(unittest.TestCase):
    """OrganisationApi unit test stubs"""

    def setUp(self):
        self.api = OrganisationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abort_addon_migration(self):
        """Test case for abort_addon_migration

        """
        pass

    def test_add_addon_tag_by_orga_and_addon_id(self):
        """Test case for add_addon_tag_by_orga_and_addon_id

        """
        pass

    def test_add_application_by_orga(self):
        """Test case for add_application_by_orga

        """
        pass

    def test_add_application_dependency_by_orga_and_app_id(self):
        """Test case for add_application_dependency_by_orga_and_app_id

        """
        pass

    def test_add_application_tag_by_orga_and_app_id(self):
        """Test case for add_application_tag_by_orga_and_app_id

        """
        pass

    def test_add_beta_tester(self):
        """Test case for add_beta_tester

        """
        pass

    def test_add_organisation_member(self):
        """Test case for add_organisation_member

        """
        pass

    def test_add_payment_method_by_orga(self):
        """Test case for add_payment_method_by_orga

        """
        pass

    def test_add_provider_feature(self):
        """Test case for add_provider_feature

        """
        pass

    def test_add_provider_plan(self):
        """Test case for add_provider_plan

        """
        pass

    def test_add_tcp_redir(self):
        """Test case for add_tcp_redir

        """
        pass

    def test_add_vhosts_by_orga_and_app_id(self):
        """Test case for add_vhosts_by_orga_and_app_id

        """
        pass

    def test_buy_drops_by_orga(self):
        """Test case for buy_drops_by_orga

        """
        pass

    def test_cancel_application_deployment_for_orga(self):
        """Test case for cancel_application_deployment_for_orga

        """
        pass

    def test_change_plan_by_orga_and_addon_id(self):
        """Test case for change_plan_by_orga_and_addon_id

        """
        pass

    def test_choose_payment_provider_by_orga(self):
        """Test case for choose_payment_provider_by_orga

        """
        pass

    def test_create_consumer_by_orga(self):
        """Test case for create_consumer_by_orga

        """
        pass

    def test_create_organisation(self):
        """Test case for create_organisation

        """
        pass

    def test_create_provider(self):
        """Test case for create_provider

        """
        pass

    def test_delete_addon_tag_by_orga_and_addon_id(self):
        """Test case for delete_addon_tag_by_orga_and_addon_id

        """
        pass

    def test_delete_application_by_orga_and_app_id(self):
        """Test case for delete_application_by_orga_and_app_id

        """
        pass

    def test_delete_application_dependency_by_orga_and_app_id(self):
        """Test case for delete_application_dependency_by_orga_and_app_id

        """
        pass

    def test_delete_application_tag_by_orga_and_app_id(self):
        """Test case for delete_application_tag_by_orga_and_app_id

        """
        pass

    def test_delete_consumer_by_orga(self):
        """Test case for delete_consumer_by_orga

        """
        pass

    def test_delete_organisation(self):
        """Test case for delete_organisation

        """
        pass

    def test_delete_payment_method_by_orga(self):
        """Test case for delete_payment_method_by_orga

        """
        pass

    def test_delete_provider(self):
        """Test case for delete_provider

        """
        pass

    def test_delete_provider_feature(self):
        """Test case for delete_provider_feature

        """
        pass

    def test_delete_provider_plan(self):
        """Test case for delete_provider_plan

        """
        pass

    def test_delete_provider_plan_feature(self):
        """Test case for delete_provider_plan_feature

        """
        pass

    def test_delete_purchase_order_by_orga(self):
        """Test case for delete_purchase_order_by_orga

        """
        pass

    def test_delete_recurrent_payment_by_orga(self):
        """Test case for delete_recurrent_payment_by_orga

        """
        pass

    def test_deprovision_addon_by_orga_and_addon_id(self):
        """Test case for deprovision_addon_by_orga_and_addon_id

        """
        pass

    def test_edit_application_by_orga_and_app_id(self):
        """Test case for edit_application_by_orga_and_app_id

        """
        pass

    def test_edit_application_env_by_orga_and_app_id_and_env_name(self):
        """Test case for edit_application_env_by_orga_and_app_id_and_env_name

        """
        pass

    def test_edit_application_environment_by_orga_and_app_id(self):
        """Test case for edit_application_environment_by_orga_and_app_id

        """
        pass

    def test_edit_organisation(self):
        """Test case for edit_organisation

        """
        pass

    def test_edit_organisation_member(self):
        """Test case for edit_organisation_member

        """
        pass

    def test_edit_provider_plan(self):
        """Test case for edit_provider_plan

        """
        pass

    def test_edit_provider_plan_feature(self):
        """Test case for edit_provider_plan_feature

        """
        pass

    def test_get_addon_by_orga_and_addon_id(self):
        """Test case for get_addon_by_orga_and_addon_id

        """
        pass

    def test_get_addon_env_by_orga_and_addon_id(self):
        """Test case for get_addon_env_by_orga_and_addon_id

        """
        pass

    def test_get_addon_instance(self):
        """Test case for get_addon_instance

        """
        pass

    def test_get_addon_instances(self):
        """Test case for get_addon_instances

        """
        pass

    def test_get_addon_migration(self):
        """Test case for get_addon_migration

        """
        pass

    def test_get_addon_migrations(self):
        """Test case for get_addon_migrations

        """
        pass

    def test_get_addon_sso_data_for_orga(self):
        """Test case for get_addon_sso_data_for_orga

        """
        pass

    def test_get_addon_tags_by_orga_id_and_addon_id(self):
        """Test case for get_addon_tags_by_orga_id_and_addon_id

        """
        pass

    def test_get_addons_by_orga_id(self):
        """Test case for get_addons_by_orga_id

        """
        pass

    def test_get_addons_linked_to_application_by_orga_and_app_id(self):
        """Test case for get_addons_linked_to_application_by_orga_and_app_id

        """
        pass

    def test_get_all_applications_by_orga(self):
        """Test case for get_all_applications_by_orga

        """
        pass

    def test_get_amount_for_orga(self):
        """Test case for get_amount_for_orga

        """
        pass

    def test_get_application_branches_by_orga_and_app_id(self):
        """Test case for get_application_branches_by_orga_and_app_id

        """
        pass

    def test_get_application_by_orga_and_app_id(self):
        """Test case for get_application_by_orga_and_app_id

        """
        pass

    def test_get_application_dependencies_by_orga_and_app_id(self):
        """Test case for get_application_dependencies_by_orga_and_app_id

        """
        pass

    def test_get_application_dependencies_env_by_orga_and_app_id(self):
        """Test case for get_application_dependencies_env_by_orga_and_app_id

        """
        pass

    def test_get_application_dependents_by_orga_and_app_id(self):
        """Test case for get_application_dependents_by_orga_and_app_id

        """
        pass

    def test_get_application_deployment_for_orga(self):
        """Test case for get_application_deployment_for_orga

        """
        pass

    def test_get_application_deployments_for_orga(self):
        """Test case for get_application_deployments_for_orga

        """
        pass

    def test_get_application_env_by_orga_and_app_id(self):
        """Test case for get_application_env_by_orga_and_app_id

        """
        pass

    def test_get_application_instance_by_orga_and_app_and_instance_id(self):
        """Test case for get_application_instance_by_orga_and_app_and_instance_id

        """
        pass

    def test_get_application_instances_by_orga_and_app_id(self):
        """Test case for get_application_instances_by_orga_and_app_id

        """
        pass

    def test_get_application_tags_by_orga_and_app_id(self):
        """Test case for get_application_tags_by_orga_and_app_id

        """
        pass

    def test_get_applications_linked_to_addon_by_orga_and_addon_id(self):
        """Test case for get_applications_linked_to_addon_by_orga_and_addon_id

        """
        pass

    def test_get_consumer_by_orga(self):
        """Test case for get_consumer_by_orga

        """
        pass

    def test_get_consumer_secret_by_orga(self):
        """Test case for get_consumer_secret_by_orga

        """
        pass

    def test_get_consumers_by_orga(self):
        """Test case for get_consumers_by_orga

        """
        pass

    def test_get_consumptions_for_orga(self):
        """Test case for get_consumptions_for_orga

        """
        pass

    def test_get_default_method_by_orga(self):
        """Test case for get_default_method_by_orga

        """
        pass

    def test_get_deployments_for_all_apps(self):
        """Test case for get_deployments_for_all_apps

        """
        pass

    def test_get_env_of_addons_linked_to_application_by_orga_and_app_id(self):
        """Test case for get_env_of_addons_linked_to_application_by_orga_and_app_id

        """
        pass

    def test_get_exposed_env_by_orga_and_app_id(self):
        """Test case for get_exposed_env_by_orga_and_app_id

        """
        pass

    def test_get_favourite_vhost_by_orga_and_app_id(self):
        """Test case for get_favourite_vhost_by_orga_and_app_id

        """
        pass

    def test_get_instances_for_all_apps_for_orga(self):
        """Test case for get_instances_for_all_apps_for_orga

        """
        pass

    def test_get_invoice_by_orga(self):
        """Test case for get_invoice_by_orga

        """
        pass

    def test_get_invoices_by_orga(self):
        """Test case for get_invoices_by_orga

        """
        pass

    def test_get_monthly_invoice_by_orga(self):
        """Test case for get_monthly_invoice_by_orga

        """
        pass

    def test_get_namespaces(self):
        """Test case for get_namespaces

        """
        pass

    def test_get_new_setup_intent_by_orga(self):
        """Test case for get_new_setup_intent_by_orga

        """
        pass

    def test_get_organisation(self):
        """Test case for get_organisation

        """
        pass

    def test_get_organisation_members(self):
        """Test case for get_organisation_members

        """
        pass

    def test_get_payment_info_for_orga(self):
        """Test case for get_payment_info_for_orga

        """
        pass

    def test_get_pdf_invoice_by_orga(self):
        """Test case for get_pdf_invoice_by_orga

        """
        pass

    def test_get_price_with_tax_by_orga(self):
        """Test case for get_price_with_tax_by_orga

        """
        pass

    def test_get_provider_features(self):
        """Test case for get_provider_features

        """
        pass

    def test_get_provider_info(self):
        """Test case for get_provider_info

        """
        pass

    def test_get_provider_plan(self):
        """Test case for get_provider_plan

        """
        pass

    def test_get_provider_plans(self):
        """Test case for get_provider_plans

        """
        pass

    def test_get_provider_tags(self):
        """Test case for get_provider_tags

        """
        pass

    def test_get_providers_info(self):
        """Test case for get_providers_info

        """
        pass

    def test_get_recurrent_payment_by_orga(self):
        """Test case for get_recurrent_payment_by_orga

        """
        pass

    def test_get_sso_data_for_orga(self):
        """Test case for get_sso_data_for_orga

        """
        pass

    def test_get_stripe_token_by_orga(self):
        """Test case for get_stripe_token_by_orga

        """
        pass

    def test_get_tcp_redirs(self):
        """Test case for get_tcp_redirs

        """
        pass

    def test_get_unpaid_invoices_by_orga(self):
        """Test case for get_unpaid_invoices_by_orga

        """
        pass

    def test_get_unpaid_invoices_by_orga1(self):
        """Test case for get_unpaid_invoices_by_orga1

        """
        pass

    def test_get_user_organisationss(self):
        """Test case for get_user_organisationss

        """
        pass

    def test_get_vhosts_by_orga_and_app_id(self):
        """Test case for get_vhosts_by_orga_and_app_id

        """
        pass

    def test_link_addon_to_application_by_orga_and_app_id(self):
        """Test case for link_addon_to_application_by_orga_and_app_id

        """
        pass

    def test_mark_favourite_vhost_by_orga_and_app_id(self):
        """Test case for mark_favourite_vhost_by_orga_and_app_id

        """
        pass

    def test_preorder_addon_by_orga_id(self):
        """Test case for preorder_addon_by_orga_id

        """
        pass

    def test_preorder_migration(self):
        """Test case for preorder_migration

        """
        pass

    def test_provision_addon_by_orga_id(self):
        """Test case for provision_addon_by_orga_id

        """
        pass

    def test_redeploy_application_by_orga_and_app_id(self):
        """Test case for redeploy_application_by_orga_and_app_id

        """
        pass

    def test_remove_application_env_by_orga_and_app_id_and_env_name(self):
        """Test case for remove_application_env_by_orga_and_app_id_and_env_name

        """
        pass

    def test_remove_organisation_member(self):
        """Test case for remove_organisation_member

        """
        pass

    def test_remove_tcp_redir(self):
        """Test case for remove_tcp_redir

        """
        pass

    def test_remove_vhosts_by_orga_and_app_id(self):
        """Test case for remove_vhosts_by_orga_and_app_id

        """
        pass

    def test_replace_addon_tags(self):
        """Test case for replace_addon_tags

        """
        pass

    def test_replace_application_tags(self):
        """Test case for replace_application_tags

        """
        pass

    def test_set_application_branch_by_orga_and_app_id(self):
        """Test case for set_application_branch_by_orga_and_app_id

        """
        pass

    def test_set_build_instance_flavor_by_orga_and_app_id(self):
        """Test case for set_build_instance_flavor_by_orga_and_app_id

        """
        pass

    def test_set_default_method_by_orga(self):
        """Test case for set_default_method_by_orga

        """
        pass

    def test_set_max_credits_per_month_by_orga(self):
        """Test case for set_max_credits_per_month_by_orga

        """
        pass

    def test_set_orga_avatar(self):
        """Test case for set_orga_avatar

        """
        pass

    def test_undeploy_application_by_orga_and_app_id(self):
        """Test case for undeploy_application_by_orga_and_app_id

        """
        pass

    def test_unlink_addon_from_application_by_orga_and_app_andd_addon_id(self):
        """Test case for unlink_addon_from_application_by_orga_and_app_andd_addon_id

        """
        pass

    def test_unmark_favourite_vhost_by_orga_and_app_id(self):
        """Test case for unmark_favourite_vhost_by_orga_and_app_id

        """
        pass

    def test_update_addon_info(self):
        """Test case for update_addon_info

        """
        pass

    def test_update_consumer_by_orga(self):
        """Test case for update_consumer_by_orga

        """
        pass

    def test_update_exposed_env_by_orga_and_app_id(self):
        """Test case for update_exposed_env_by_orga_and_app_id

        """
        pass

    def test_update_provider_infos(self):
        """Test case for update_provider_infos

        """
        pass


if __name__ == '__main__':
    unittest.main()
