"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.addon_plan_view import AddonPlanView
from openapi_client.model.addon_provider_info_view import AddonProviderInfoView
globals()['AddonPlanView'] = AddonPlanView
globals()['AddonProviderInfoView'] = AddonProviderInfoView
from openapi_client.model.addon_view import AddonView


class TestAddonView(unittest.TestCase):
    """AddonView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddonView(self):
        """Test AddonView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddonView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
