"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.setup_intent_view import SetupIntentView
globals()['SetupIntentView'] = SetupIntentView
from openapi_client.model.stripe_confirmation_error_message import StripeConfirmationErrorMessage


class TestStripeConfirmationErrorMessage(unittest.TestCase):
    """StripeConfirmationErrorMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStripeConfirmationErrorMessage(self):
        """Test StripeConfirmationErrorMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StripeConfirmationErrorMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
