"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.super_nova_flavor import SuperNovaFlavor
globals()['SuperNovaFlavor'] = SuperNovaFlavor
from openapi_client.model.super_nova_instance_view import SuperNovaInstanceView


class TestSuperNovaInstanceView(unittest.TestCase):
    """SuperNovaInstanceView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuperNovaInstanceView(self):
        """Test SuperNovaInstanceView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuperNovaInstanceView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
