"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.addon_application_summary import AddonApplicationSummary


class TestAddonApplicationSummary(unittest.TestCase):
    """AddonApplicationSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddonApplicationSummary(self):
        """Test AddonApplicationSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddonApplicationSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
