"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.addon_feature_instance_view import AddonFeatureInstanceView
globals()['AddonFeatureInstanceView'] = AddonFeatureInstanceView
from openapi_client.model.wannabe_addon_plan import WannabeAddonPlan


class TestWannabeAddonPlan(unittest.TestCase):
    """WannabeAddonPlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWannabeAddonPlan(self):
        """Test WannabeAddonPlan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WannabeAddonPlan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
