"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.o_auth1_consumer_summary import OAuth1ConsumerSummary


class TestOAuth1ConsumerSummary(unittest.TestCase):
    """OAuth1ConsumerSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth1ConsumerSummary(self):
        """Test OAuth1ConsumerSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OAuth1ConsumerSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
