"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.owner_view import OwnerView
from openapi_client.model.user_view import UserView
globals()['OwnerView'] = OwnerView
globals()['UserView'] = UserView
from openapi_client.model.recurrent_payment_view import RecurrentPaymentView


class TestRecurrentPaymentView(unittest.TestCase):
    """RecurrentPaymentView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecurrentPaymentView(self):
        """Test RecurrentPaymentView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecurrentPaymentView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
