"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.products_api import ProductsApi  # noqa: E501


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bill_owner(self):
        """Test case for bill_owner

        """
        pass

    def test_edit_application_configuration(self):
        """Test case for edit_application_configuration

        """
        pass

    def test_end_addon_migration(self):
        """Test case for end_addon_migration

        """
        pass

    def test_get_addon_provider(self):
        """Test case for get_addon_provider

        """
        pass

    def test_get_addon_provider_infos(self):
        """Test case for get_addon_provider_infos

        """
        pass

    def test_get_addon_provider_versions(self):
        """Test case for get_addon_provider_versions

        """
        pass

    def test_get_addon_providers(self):
        """Test case for get_addon_providers

        """
        pass

    def test_get_application_info(self):
        """Test case for get_application_info

        """
        pass

    def test_get_available_instances(self):
        """Test case for get_available_instances

        """
        pass

    def test_get_available_packages(self):
        """Test case for get_available_packages

        """
        pass

    def test_get_countries(self):
        """Test case for get_countries

        """
        pass

    def test_get_country_codes(self):
        """Test case for get_country_codes

        """
        pass

    def test_get_excahnge_rates(self):
        """Test case for get_excahnge_rates

        """
        pass

    def test_get_flavors(self):
        """Test case for get_flavors

        """
        pass

    def test_get_instance(self):
        """Test case for get_instance

        """
        pass

    def test_get_mfa_kinds(self):
        """Test case for get_mfa_kinds

        """
        pass

    def test_get_zones(self):
        """Test case for get_zones

        """
        pass

    def test_list_apps(self):
        """Test case for list_apps

        """
        pass

    def test_logscollector(self):
        """Test case for logscollector

        """
        pass

    def test_provision_other_addon(self):
        """Test case for provision_other_addon

        """
        pass


if __name__ == '__main__':
    unittest.main()
