"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.end_of_invoice_error import EndOfInvoiceError


class TestEndOfInvoiceError(unittest.TestCase):
    """EndOfInvoiceError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndOfInvoiceError(self):
        """Test EndOfInvoiceError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EndOfInvoiceError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
