"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.addon_feature_instance_view import AddonFeatureInstanceView
globals()['AddonFeatureInstanceView'] = AddonFeatureInstanceView
from openapi_client.model.addon_plan_view import AddonPlanView


class TestAddonPlanView(unittest.TestCase):
    """AddonPlanView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddonPlanView(self):
        """Test AddonPlanView"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddonPlanView()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
