"""
    Clever-Cloud API

    Public API for managing Clever-Cloud data and products  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support@clever-cloud.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.wannabe_oauth_app import WannabeOauthApp
    globals()['WannabeOauthApp'] = WannabeOauthApp


class WannabeApplication(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('instance_lifetime',): {
            'REGULAR': "REGULAR",
            'MIGRATION': "MIGRATION",
            'TASK': "TASK",
        },
        ('force_https',): {
            'ENABLED': "ENABLED",
            'DISABLED': "DISABLED",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'name': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'zone': (str,),  # noqa: E501
            'deploy': (str,),  # noqa: E501
            'shutdownable': (bool,),  # noqa: E501
            'instance_type': (str,),  # noqa: E501
            'instance_version': (str,),  # noqa: E501
            'instance_variant': (str,),  # noqa: E501
            'instance_lifetime': (str,),  # noqa: E501
            'min_instances': (int,),  # noqa: E501
            'max_instances': (int,),  # noqa: E501
            'min_flavor': (str,),  # noqa: E501
            'max_flavor': (str,),  # noqa: E501
            'tags': ([str],),  # noqa: E501
            'archived': (bool,),  # noqa: E501
            'sticky_sessions': (bool,),  # noqa: E501
            'homogeneous': (bool,),  # noqa: E501
            'favourite': (bool,),  # noqa: E501
            'cancel_on_push': (bool,),  # noqa: E501
            'separate_build': (bool,),  # noqa: E501
            'build_flavor': (str,),  # noqa: E501
            'oauth_service': (str,),  # noqa: E501
            'oauth_app_id': (str,),  # noqa: E501
            'oauth_app': (WannabeOauthApp,),  # noqa: E501
            'appliance_id': (str,),  # noqa: E501
            'branch': (str,),  # noqa: E501
            'force_https': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'name': 'name',  # noqa: E501
        'description': 'description',  # noqa: E501
        'zone': 'zone',  # noqa: E501
        'deploy': 'deploy',  # noqa: E501
        'shutdownable': 'shutdownable',  # noqa: E501
        'instance_type': 'instanceType',  # noqa: E501
        'instance_version': 'instanceVersion',  # noqa: E501
        'instance_variant': 'instanceVariant',  # noqa: E501
        'instance_lifetime': 'instanceLifetime',  # noqa: E501
        'min_instances': 'minInstances',  # noqa: E501
        'max_instances': 'maxInstances',  # noqa: E501
        'min_flavor': 'minFlavor',  # noqa: E501
        'max_flavor': 'maxFlavor',  # noqa: E501
        'tags': 'tags',  # noqa: E501
        'archived': 'archived',  # noqa: E501
        'sticky_sessions': 'stickySessions',  # noqa: E501
        'homogeneous': 'homogeneous',  # noqa: E501
        'favourite': 'favourite',  # noqa: E501
        'cancel_on_push': 'cancelOnPush',  # noqa: E501
        'separate_build': 'separateBuild',  # noqa: E501
        'build_flavor': 'buildFlavor',  # noqa: E501
        'oauth_service': 'oauthService',  # noqa: E501
        'oauth_app_id': 'oauthAppId',  # noqa: E501
        'oauth_app': 'oauthApp',  # noqa: E501
        'appliance_id': 'applianceId',  # noqa: E501
        'branch': 'branch',  # noqa: E501
        'force_https': 'forceHttps',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """WannabeApplication - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            name (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            zone (str): [optional]  # noqa: E501
            deploy (str): [optional]  # noqa: E501
            shutdownable (bool): [optional]  # noqa: E501
            instance_type (str): [optional]  # noqa: E501
            instance_version (str): [optional]  # noqa: E501
            instance_variant (str): [optional]  # noqa: E501
            instance_lifetime (str): [optional]  # noqa: E501
            min_instances (int): [optional]  # noqa: E501
            max_instances (int): [optional]  # noqa: E501
            min_flavor (str): [optional]  # noqa: E501
            max_flavor (str): [optional]  # noqa: E501
            tags ([str]): [optional]  # noqa: E501
            archived (bool): [optional]  # noqa: E501
            sticky_sessions (bool): [optional]  # noqa: E501
            homogeneous (bool): [optional]  # noqa: E501
            favourite (bool): [optional]  # noqa: E501
            cancel_on_push (bool): [optional]  # noqa: E501
            separate_build (bool): [optional]  # noqa: E501
            build_flavor (str): [optional]  # noqa: E501
            oauth_service (str): [optional]  # noqa: E501
            oauth_app_id (str): [optional]  # noqa: E501
            oauth_app (WannabeOauthApp): [optional]  # noqa: E501
            appliance_id (str): [optional]  # noqa: E501
            branch (str): [optional]  # noqa: E501
            force_https (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """WannabeApplication - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            name (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            zone (str): [optional]  # noqa: E501
            deploy (str): [optional]  # noqa: E501
            shutdownable (bool): [optional]  # noqa: E501
            instance_type (str): [optional]  # noqa: E501
            instance_version (str): [optional]  # noqa: E501
            instance_variant (str): [optional]  # noqa: E501
            instance_lifetime (str): [optional]  # noqa: E501
            min_instances (int): [optional]  # noqa: E501
            max_instances (int): [optional]  # noqa: E501
            min_flavor (str): [optional]  # noqa: E501
            max_flavor (str): [optional]  # noqa: E501
            tags ([str]): [optional]  # noqa: E501
            archived (bool): [optional]  # noqa: E501
            sticky_sessions (bool): [optional]  # noqa: E501
            homogeneous (bool): [optional]  # noqa: E501
            favourite (bool): [optional]  # noqa: E501
            cancel_on_push (bool): [optional]  # noqa: E501
            separate_build (bool): [optional]  # noqa: E501
            build_flavor (str): [optional]  # noqa: E501
            oauth_service (str): [optional]  # noqa: E501
            oauth_app_id (str): [optional]  # noqa: E501
            oauth_app (WannabeOauthApp): [optional]  # noqa: E501
            appliance_id (str): [optional]  # noqa: E501
            branch (str): [optional]  # noqa: E501
            force_https (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
